services:
  db_pg_1:
    image: postgres:latest
    environment:
      POSTGRES_DB: taskMaster
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5